### ISSUE TITLE
TypeError: Cannot assign to read only property 'id' of 0

### ISSUE THREAD

**Issue by WeeJeWel** [sqmk/huejay#74] opened 2016-12-29 20:01 UTC
Pretty simple error catched when doing a `client.scenes.getAll()`

```
TypeError: Cannot assign to read only property 'id' of 0
    at /node_modules/huejay/lib/Command/Scene/GetScenes.js:27:30
    at Array.map (native)
    at /node_modules/huejay/lib/Command/Scene/GetScenes.js:26:36
```

The weird part is, it's happening on one of my project user's device, but I tested with him and this was the catched error.

**Comment by kixeye-opensource** [comment] 2016-12-29 23:48
Interesting. I'll see if I can reproduce.

**Comment by sqmk** [comment] 2016-12-30 00:00
I can investigate. Can your project user post what version his/her bridge API is?

**Comment by jeroenbos22** [comment] 2017-01-08 09:37
That user is me :). My Api version is 1.16.0 (Hue bridge v1).

**Comment by jeroenbos22** [comment] 2017-01-08 10:04
Ok, while searching for the version number I noticed my json looked weird. Had a lot of scenes version 1 that didnt exist anymore. Did a cleanup of the hub and now there are only v2 scenes and now it works again! So think it has to do with the V1 scenes since the error state: Cannot assign to read only property 'id' of 0. 0, the first scene was a non existing V1 scene.

So for me it works now but could be helpfull for other users with V1 scenes.

**Comment by sqmk** [comment] 2017-01-09 02:11
Interesting. Perhaps the older scenes didn't have "id" property then. Good to know! Thanks for checking in.

**Closed** 2017-01-09 02:11 UTC

**Comment by WeeJeWel** [comment] 2017-01-09 16:10
@sqmk Maybe you can add a check so it doesn't crash, though?
