### ISSUE TITLE
Memory leak (?)

### ISSUE THREAD

**Issue by WeeJeWel** [sqmk/huejay#85] opened 2017-11-30 10:47 UTC
An implementation of this module is very similar to other implementations, with the major difference this library. Users have reported the memory increasing steadily here: https://github.com/athombv/nl.philips.hue/issues/93

However hard to prove, I'd bet a bottle of wine it's a memory leak in the huejay library (or one of their dependencies).

**Comment by sqmk** [comment] 2017-11-30 13:46
I need to understand how you are using this module and what your use cases are so I can simulate activity. Eg. what commands are being used, how often do you instantiate and destroy huejay client objects, etc.

**Comment by sqmk** [comment] 2017-11-30 17:12
I've benchmarked the latest Huejay by slamming my local bridge with `client.lights.getAll`, `client.lights.getById`, and `client.lights.save` for about an hour, at a significant rate (several requests within 100ms). I also made sure the exception/error handling by Huejay was invoked when the bridge was overloaded (and with general invalid requests). I took heap dumps over the course of the hour and compared deltas between dumps, and so far, nothing is indicative of a memory leak with the library.

I did not test timepatterns or conditions, which happen to be the only things that use dependencies `moment` and `sprintf-js`. My testing only touched on `axios`. Because those dependencies and features that rely on them are rarely used, I'm convinced those aren't the cause of the leaks your users are experiencing.

Providing a list of commonly called commands in the app mentioned would be helpful as I can tune and bias my profiling towards them. The behavior with other commands will be comparable to the three I benchmarked, and I presume the results will be the same. I am happy to test those other commands regardless.

**Comment by WeeJeWel** [comment] 2017-12-01 10:42
Thank you for testing so extensively. I also could not find a memory leak myself, both by testing huejay standalone as well as the implementation. But there are many users with the same code who run into this issue so it is probably an edge case (maybe if the bridge is offline?).

The commands used:

```
lights.getAll() // every 5s
sensors.getAll() // every 5s
discover({ strategy: 'nupnp' }) // every 60s
discover({ strategy: 'upnp' }) // every 60s
light.save() // sporadically 
sensor.save() // sporadically
```

**Comment by sqmk** [comment] 2018-02-04 22:57
Closing as I don't think this library is responsible for the leaks.

**Closed by sqmk** 2018-02-04 22:57 UTC
